apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    app: backend-php
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend-php
  template:
    metadata:
      labels:
        app: backend-php
    spec:
      containers:
      - name: backend-php
        image: denilsonbonatti/k8s-projeto1-app-base
        ports:
        - containerPort: 80